In [5]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true      = np.array([0.3,0.7,1,0,0.5])

In [2]:
def mae(y_true,y_predicted) :
  total_error = 0
  for yt,yp in zip(y_true,y_predicted) :
    total_error += abs(yt-yp)
  print("Total error : ", total_error)

  mae = total_error / len(y_true)
  print("MAE : ",mae)
  return mae

In [7]:
mae(y_true,y_predicted)

Total error :  2.5
MAE :  0.5


0.5

In [8]:
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [11]:
# Log loss
epsilon = 1e-15 #

In [13]:
y_predicted_new = [max(i,epsilon) for i in y_predicted] #
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [16]:
# 즉, 1은 1이 아니라, 1에 최대한 가까운 수로(1보다 작음)
# 0은 0이 아니라, 0에 최대한 가까운 수로 바꾸고자 하는 것(양수)
y_predicted_new = [min(i,1-epsilon) for i in y_predicted]
-y_predicted_new

[0.999999999999999, 0.999999999999999, 0, 0, 0.999999999999999]

In [17]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([-9.99200722e-16, -9.99200722e-16,            -inf,            -inf,
       -9.99200722e-16])

In [18]:
np.log(y_predicted_new) # 각각의 값에  log를 취해주는 것


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([-9.99200722e-16, -9.99200722e-16,            -inf,            -inf,
       -9.99200722e-16])

In [19]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [20]:
log_loss(y_true, y_predicted)

17.2696280766844

In [ ]:
# mse
np.mean(np.square(y_true-y_predicted))